#! /usr/bin/bash

PARAMS=params.properties
timestamp="$(date +"%m%d_%T")"
java -ea -Xmx8G  -Dfile.encoding=UTF-8 -Djava.library.path=lib/ -classpath "./lib/*:./out/production/Morphology" Main $PARAMS >outputs_time/$timestamp;
